### ISSUE TITLE
Deal with stack size limit exceptions

### ISSUE THREAD

**Issue by RelativeForce** [michalkonecny/robust-plots#104]
## Details:
Hours Spent: 8

## Background
Occasionally we get a silent failure with "stack size limit exceeded" exception showing on the JS console.

## Overview
Investigate what is responsible for this exception and try to fix it or at least detect it. 

## Acceptance Criteria
- [x] There are no exceptions or exceptions are reported on a range of stress tests.

## Closing Notes

Overview of changes can be found in PR _PR ID HERE_

**Comment by michalkonecny** [comment]
I am currently struggling to reproduce the exception despite trying quite hard.
